repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-xml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: dprint
        name: dprint
        language: system
        entry: dprint fmt
        pass_filenames: false
      - id: actionlint
        name: actionlint
        language: system
        entry: actionlint
        pass_filenames: false
      - id: zizmor
        name: zizmor
        language: system
        entry: zizmor --persona auditor
        files: \.github/workflows/
        types: [yaml]
      - id: hadolint
        name: hadolint
        language: system
        entry: hadolint
        files: Dockerfile
        types: [file]
      - id: ruff-check
        name: ruff check
        language: system
        entry: ruff check --force-exclude
        types: [python]
        pass_filenames: true
      - id: py-compile
        name: Compile Python files
        entry: python -m py_compile
        language: system
        types: [python]
        pass_filenames: true
      - id: trufflehog
        name: trufflehog
        language: system
        entry: trufflehog git file://. --only-verified --fail
        pass_filenames: false
