[settings]
python.precompiled_flavor = "install_only_stripped"
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[tools]
actionlint = "1.7.12"
dprint = "0.55.1"
git-cliff = "2.13.1"
hadolint = "2.14.0"
k3d = "5.9.0"
kubectl = "1.36.2"
ruff = "0.15.20"
shellcheck = "0.11.0"
tilt = "0.37.4"
trufflehog = "3.95.7"
zizmor = "1.26.1"
node = "24.18.0"
python = "3.14.6"
uv = "0.11.26"
buildifier = "8.5.1"
k6 = "2.1.0"
prek = "0.4.6"
