[settings]
python.precompiled_flavor = "install_only_stripped"

[tools]
actionlint = "1.7.12"
dprint = "0.54.0"
git-cliff = "2.12.0"
hadolint = "2.14.0"
k3d = "5.8.3"
kubectl = "1.35.3"
ruff = "0.15.10"
shellcheck = "0.11.0"
tilt = "0.37.1"
trufflehog = "3.93.6"
zizmor = "1.22.0"
node = "24.14.1"
python = "3.14.4"
uv = "0.11.6"
buildifier = "8.5.1"
k6 = "1.6.1"
prek = "0.3.6"
