---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  doh.conf: |
    server {
        listen 443 ssl;
        listen 443 quic reuseport;
        http2 on;
        http3 on;

        ssl_certificate     /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        ssl_session_timeout    1d;
        ssl_session_cache      shared:SSL:10m;
        ssl_session_tickets    off;
        ssl_protocols          TLSv1.3;

        add_header Alt-Svc                   'h3=":443"; ma=86400' always;
        add_header X-XSS-Protection          "1; mode=block" always;
        add_header X-Content-Type-Options    "nosniff" always;
        add_header Referrer-Policy           "no-referrer-when-downgrade" always;
        add_header Content-Security-Policy   "default-src 'self' http: https: ws: wss: data: blob: 'unsafe-inline'; frame-ancestors 'self';" always;
        add_header Permissions-Policy        "interest-cohort=()" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

        proxy_http_version    1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_connect_timeout              60s;
        proxy_send_timeout                 60s;
        proxy_read_timeout                 60s;

        location ~ /\.(?!well-known) {
            deny all;
        }

        location /test-default/ {
            proxy_pass http://worker-default:8787/;
        }

        location /test-no-ecs-no-rebind/ {
            proxy_pass http://worker-no-ecs-no-rebind:8787/;
        }

        location /test-no-token/ {
            proxy_pass http://worker-no-token:8787/;
        }

        location /test-ecs-mock/ {
            proxy_pass http://worker-ecs-mock:8787/;
        }

        location /mock-doh/ {
            proxy_pass http://mock-doh:8080/;
        }

        location = /favicon.ico {
            log_not_found off;
            access_log    off;
        }

        location = /robots.txt {
            log_not_found off;
            access_log    off;
        }
    }
