---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - port: 8787
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: k3d-doh-registry:5001/doh-worker
          ports:
            - name: http
              containerPort: 8787
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /usr/src/app/worker/config.py
              subPath: config.py
            - name: dev-vars
              mountPath: /usr/src/app/.dev.vars
              subPath: .dev.vars
          startupProbe:
            httpGet:
              path: /health
              port: 8787
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8787
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8787
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: worker-config
        - name: dev-vars
          configMap:
            name: worker-dev-vars
