# Copyright 2025-2026 Trevor Lauder.
# SPDX-License-Identifier: MIT

# Generated by scripts/build_blocklist.py
# Do not edit manually

bloom_k: int = 33
exact_count: int = 81934
bloom_shards: int = 1
source_urls: list[str] = [
    "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
]
shard_m: list[int] = [3926712]
