# Copyright 2025-2026 Trevor Lauder.
# SPDX-License-Identifier: MIT

# Generated by scripts/build_blocklist.py
# Do not edit manually

bloom_k: int = 0
exact_count: int = 0
bloom_shards: int = 0
source_urls: list[str] = []
shard_m: list[int] = []
