# Copyright 2025-2026 Trevor Lauder.
# SPDX-License-Identifier: MIT

# Generated by scripts/build_blocklist.py
# Do not edit manually

bloom_m: int = 3926760
bloom_k: int = 33
exact_count: int = 81935
bloom_shards: int = 0
source_urls: list[str] = [
    "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
]
shard_m: list[int] = []
