# Copyright 2025-2026 Trevor Lauder.
# SPDX-License-Identifier: MIT

# Generated by scripts/build_blocklist.py
# Do not edit manually

filter_type: str = "bfuse32"
exact_count: int = 0
shard_count: int = 0
source_urls: list[str] = []
